"""
This is the main process of task1, including get response from llama model and entity linking.
Input: test_data/input.txt
Output: test_data/output.txt
Model: the llama model here is different from model in docker, I install one locally for debugging.
To run this file in docker, just change the model_path.
"""
import os

# avoid huggingface tokenizers warning about forking
os.environ["TOKENIZERS_PARALLELISM"] = "false"
import sys, argparse
from src.entity_linking import EntityLinking, Entity
from src.llama_wrap import LlamaWrapper, MODEL_LLAMA_2, MODEL_LLAMA_3
from src.question_classification import QuestionClassifier, QUESTION_TYPE_STATEMENT, QUESTION_TYPE_BOOLEAN, QUESTION_TYPE_ENTITY
from src.conclusion import Conclusion
from src.qa_statement import Statement
from src.coreNLP_wrap import RelationTriple
from src.fact_check import FactCheck

def parse_question(text):
    """
    Parse the input file, breaks down each line into question ID and question, and saves them in a dictionary    
    
    Args:
    text: Content of the input file.
    
    Returns:
    dict: A dictionary with question IDs as keys and questions as values.
    """
    question_dict = {}
    lines = text.split("\n")
    lines = [x+"\n" for x in lines if x]

    for line in lines:
        # split "Q1<TAB>string"
        key_value = line.strip().split("\t")
        
        if len(key_value) == 2:
            key, value = key_value
            question_dict[key] = {'Q': value}
    return question_dict



def generate_entity(question, response) -> list[Entity]:
    """
    Generates entity links from a given question and its response.
    
    Args:
    question (str): The original question.
    response (str): The response generated by the model.
    
    Returns:
    list: all entities recognized list[Entity]
    """
    el = EntityLinking(50)
    text = question + " " + response
    entities = el.link(text)

    return entities

def generate_all_answer(question_dict, llama_wrapper:LlamaWrapper):
    """
    Processes all questions to generate responses and entity links, and save them in the dictionary.
    
    Args:
    question_dict (dict): Dictionary containing questions.
    
    Returns:
    dict: Updated dictionary with responses and entity links.
    """
    for question_id in question_dict.keys():
        question = question_dict[question_id]['Q']
        # get response from llama model
        response = llama_wrapper.generate(question)
        question_dict[question_id]['R'] = response
        # entity linking
        entities = generate_entity(question, response)
        question_dict[question_id]['E'] = entities
    return question_dict

def post_process(question_dict):
    """
    generate a clear answer and check the correctness of answer
    """

    classifier = QuestionClassifier()
    concluder = Conclusion()
    statement =  Statement()
    fact =  FactCheck()
    relation = RelationTriple()

    for question_id in question_dict.keys():
        question = question_dict[question_id]['Q']
        response = question_dict[question_id]['R']
        entities = question_dict[question_id]['E']
        # entity_dict = {entity.mention: entity.get_wikipedia_page() for entity in entities}
        if 'Question:' in question:
            question = question.replace('Question:', '').strip()
        if 'Answer:' in question:
            question = question.replace('Answer:', '').strip()

        # classify question as entity, yes/no, statement, and generate answer from model response
        question_type = classifier.classify(question)
        if question_type in [QUESTION_TYPE_STATEMENT, QUESTION_TYPE_BOOLEAN]:
            answer = concluder.conclude_yn(question, response)
            question_dict[question_id]['A'] = answer 
        else:
            concluded_entity = concluder.conclude_entity(question,question+" "+response,entities)
            wiki_link = concluded_entity.wikipedia_link
            question_dict[question_id]['A'] = wiki_link
            answer = concluded_entity.mention
        
        

        state = statement.construct_statement(question_type, question, answer)
        
        triple, subject, obj = relation.get_triples(state, entities)
        if subject and obj: # if triplet has entities as subject and object
            check_ans = fact.if_triple_exists(triple, subject, obj)
            if question_type == QUESTION_TYPE_BOOLEAN or question_type == QUESTION_TYPE_STATEMENT:
                if (answer=='yes' and check_ans is True) or (answer=='no' and check_ans is False):
                    correctness = 'correct'
                else:
                    correctness = 'incorrect'
            else:
                if check_ans is True:
                    correctness = 'correct'
                else:
                    correctness = 'incorrect'
        else: # for questions that has no relation triple like <E, relation(str), E> 
            if question_type == QUESTION_TYPE_BOOLEAN or question_type == QUESTION_TYPE_STATEMENT:
                if fact.fact_check_yn_using_concluder(question, response, answer, entities):
                    correctness = 'correct'
                else:
                    correctness = 'incorrect'
            else:
                if fact.fact_check_entity_using_concluder(question, response, state, concluded_entity):
                    correctness = 'correct'
                else:
                    correctness = 'incorrect'
        question_dict[question_id]['C'] = correctness
    
    return question_dict

def format_output(output_dict):
    """
    Formats the output dictionary into a string suitable for saving to a file.
    
    Args:
    output_dict (dict): The dictionary containing questions, responses, and entity links.
    
    Returns:
    str: A formatted string representing the output data.
    """    
    output = ""

    for i in output_dict.keys():
        output += (f"{i}\tR\"{output_dict[i]['R']}\"\n")
        output += (f"{i}\tA\"{output_dict[i]['A']}\"\n")
        output += (f"{i}\tC\"{output_dict[i]['C']}\"\n")
        for entity in output_dict[i]['E']:
            output += (f"{i}\tE\"{entity.mention}\"\t\"{entity.get_wikipedia_page()}\"\n")

    output = output.strip()

    return output

def main_task(input, llama_wrapper:LlamaWrapper):
    """
    Integrate all processes of all tasks

    Args:
    input_path (str): Path to the input file containing questions.
    output_path (str): Path to the output file.
    """
    
    # read questions into a dictionary
    question_dict = parse_question(input)
    # append response and entity linking into the dictionary
    ret_dict = generate_all_answer(question_dict, llama_wrapper)
    ret_dict = post_process(ret_dict)

    return format_output(ret_dict)

if __name__=="__main__":    
    if not sys.stdin.isatty():  # Detect if input is piped
        input_text = sys.stdin.read()
    else:
        print("No input. Pipe input to this script.")
        exit(1)

    parser = argparse.ArgumentParser(description="Process input with arguments")
    parser.add_argument("--llama_ver", type=int, default=2 , required=False, help="llama version, 2 or 3")
    parser.add_argument("--output", type=str, required=False, help="output file path")
    args = parser.parse_args()
    llama_ver = args.llama_ver

    if llama_ver == 2:
        llama_ver = MODEL_LLAMA_2
    else:
        llama_ver = MODEL_LLAMA_3
    llama = LlamaWrapper(llama_ver)

    output = main_task(input_text, llama)
    print(output)

    if args.output:
        with open(args.output, "w") as f:
            f.write(output)

 

