# idea and code from: Joel

import os,sys
from llama_cpp import Llama

MODEL_LLAMA_2 = "llama-2"
MODEL_LLAMA_3 = "llama-3"

def suppress_output():
    """
    Suppresses stdout and stderr output to avoid cluttering the console during the initialization of the Llama model.
    """
    sys.stdout = open(os.devnull, 'w')
    sys.stderr = open(os.devnull, 'w')

def restore_output():
    """
    Restores stdout and stderr output to their original settings.
    """
    sys.stdout = sys.__stdout__
    sys.stderr = sys.__stderr__


class LlamaWrapper:
    def __init__(self, model, max_tokens=64):
        self.max_tokens = max_tokens
        if model == MODEL_LLAMA_2:
            self.llama = self.__load_llama_2()
            self.gen_func = self.__generate_llama_2
        elif model == MODEL_LLAMA_3:
            self.llama = self.__load_llama_3()
            self.gen_func = self.__generate_llama_3        

    def generate(self, question):
        return self.gen_func(question)

    def __load_llama_3(self):
        suppress_output()
        ret = self.llama = Llama.from_pretrained(
            repo_id="bartowski/Llama-3.2-1B-Instruct-GGUF",
            filename="Llama-3.2-1B-Instruct-Q6_K_L.gguf",
            cache_dir=os.getenv('MODELS_CACHE','./models_cache/hub'),
            verbose=False
        )
        restore_output()
        return ret
    
    def __load_llama_2(self):
        # check if the model exists
        suppress_output()
        if not os.path.exists("/home/user/models/llama-2-7b.Q4_K_M.gguf"):
            raise FileNotFoundError("Model not found at /home/user/models/llama-2-7b.Q4_K_M.gguf")
        ret = Llama(model_path="/home/user/models/llama-2-7b.Q4_K_M.gguf", verbose=False)
        restore_output()
        return ret

    def __generate_llama_2(self, question):
        """
        Generates a response from the Llama model for a given question.
        
        Args:
        question (str): The question to be answered by the model.
        
        Returns:
        str: The response generated by the model.
        """
        prompt = question
        if not (
          question.startswith("Q:") or question.startswith("Question:")
          or question.startswith("q: ") or question.startswith("question: ")):
            prompt = 'Q:' + question + ' A:'
        model_output = self.llama(prompt, max_tokens=self.max_tokens, echo=True, stop=["Q:", "\n"])
        response = model_output["choices"][0]["text"].strip()
        response = response[len(prompt):].strip()
        response = response.replace("\n", " ")
        return response
    
    def __generate_llama_3(self, question):
        model_output = self.llama.create_chat_completion(
            messages = [
                {
                    "role": "user",
                    "content": question
                }
            ],
            max_tokens=self.max_tokens
        )
        response = model_output['choices'][0]['message']['content'].strip()
        response = response.replace("\n", " ")
        return response
